### ISSUE TITLE
injectViews method should call super.injectViews method if the superclass contains @InjectView annotation.

### ISSUE THREAD

**Issue by s0nerik** [Arasthel/SwissKnife#30]
I've noticed that injectViews method works not correctly when used the @InjectView annotation is used both in the actual class and some of it's superclasses. The easy way to solve it should be just to call the superclass's injectViews method if the superclass contains @InjectView annotation.

**Comment by Arasthel** [comment]
Could you try with [this branch](https://github.com/Arasthel/SwissKnife/tree/parcelablelisttest)? I've tested a few things and it seems to work well so far, but let us make sure.

**Comment by s0nerik** [comment]
Actually, it doesn't work the way I expect it to work.
Having a structure like this causes a `btn1` to be `null` while it should be present after injecting views into `InheritedActivity`.

**BaseActivity**:
```
@CompileStatic
class BaseActivity extends AppCompatActivity {

    @InjectView(R.id.btn1)
    Button btn1

}
```
**BaseActivity**:
```
@CompileStatic
class BaseActivity extends AppCompatActivity {

    @InjectView(R.id.btn1)
    Button btn1

}
```

**Comment by Arasthel** [comment]
Actually, what I do is check if any of the parent classes has an `injectViews` method. If it didn't work for you, maybe this way is flawed because at the moment `InheritedActivity` is being processed, `BaseActivity` hasn't been processed yet and that method isn't there.

But looking for fields only covers the view injection part, not the listener injection. If you have a class which only has an `@OnClick` on a button and you extend it, this new class wouldn't have that listener injected as no `super.injectViews(...)` would be called.

**Comment by s0nerik** [comment]
You're most probably right about the `BaseActivity` not being processed at the moment `InheritedActivity` is processing. But as far as I remember, there's no way to ensure the order of  classes being processed by the same AST transformation. So, basically, I see two ways to overcome the issue with injections other than those for Views. First of all, we can look for occurrences of methods/fields annotated with all the other needed annotations in superclasses just like I've done with `@InjectView` and `@InjectViews`. The other possible way I can imagine is to create a new annotation that will be applied by the user to the base classes, and we will need just to determine if any of superclasses is annotated with it to know if we need to super.injectViews() method. IMHO the first method is better, `cause it won't force user to annotate base classes with another annotation.
