### ISSUE TITLE
SwissKnife.inject(Object target, View view) does not work in some conditions

### ISSUE THREAD

**Issue by ghost** [Arasthel/SwissKnife#41]
I've been trying to use SwissKnife injection to implement the holder pattern on a `ListView`. In my project, I have several `ListView`. But, on one of them, the injection works, for the others, it fails with:

```
groovy.lang.MissingMethodException:
    No signature of method: java.lang.Object.injectViews() is
    applicable for argument types: (android.widget.LinearLayout) values:
    [android.widget.LinearLayout{288e7075 V.E..... ......I. 0,0-0,0}]
```

**Comment by ghost** [comment]
Some more precisions : 

I've written an `AbstractAdatater` which has a method in charge of initializing the holder and inject the views or retrive it from the view [here](https://github.com/AugierLe42e/Phoebius/blob/develop/app/src/main/groovy/augier/fr/phoebius/utils/AbstractAdaptater.groovy#L25). Calling that method always throw the above mentionned exception. The exact same piece of code used [here](https://github.com/AugierLe42e/Phoebius/blob/develop/app/src/main/groovy/augier/fr/phoebius/UI/AlbumListFragment.groovy#L69) works correctly and injects the views into the holder. But, the still same exact piece of code used [here](https://github.com/AugierLe42e/Phoebius/blob/develop/app/src/main/groovy/augier/fr/phoebius/UI/SongListFragment.groovy#L111) or [here](https://github.com/AugierLe42e/Phoebius/blob/develop/app/src/main/groovy/augier/fr/phoebius/UI/PlaylistsFragment.groovy#L52) then throws again the exception.

**Comment by jmartinesp** [comment]
From what I've seen, the code fails when trying to use inject on the `T`, since decompiling the code - using `@CompileStatic`, gives you this:

``` groovy
Object holder = null;
...
v = LayoutInflater.from((Context)a).inflate(layoutId, vg, false);
holder = new Object();
SwissKnife.inject(holder, v);
v.setTag(holder);
```

Because of this the `SwissKnife.inject()` method treats holder as an `Object` and tries to find the `injectViews` method on the `Object` class.

This might be due to a bad decompilation, but it doesn't seem to be the case. It also doesn't work when trying to cast it to `T` again using `(T) holder` or `holder as T`. I even tried to make a typed `inject` method or calling `holder.injectViews(v)` manually, but it didn't help at all.

Maybe you could rely on some abstract `getHolder()` method of the adapter which is overriden in each implementation, that way that `holder = new Object()` wouldn't take place at all.

**Comment by eugene-kamenev** [comment]
@AugierLe42e as advice try using different java decompilers with [this library](https://github.com/Konloch/bytecode-viewer). And yes always use \@CompileStatic

**Comment by jmartinesp** [comment]
Since this bug doesn't seem to be SK-related, I'm closing the issue :+1:
